name: React deploy # Workflow 이름
on: # Event 감지
  workflow_dispatch

jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: npm i

      - name: Build # React Build
        run: npm run build
        env:
          CI: false

      - name: Deploy build outputs
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: ${{ secrets.PORT }}
          source: "build/*"
          strip_components: 1
          target: "/home/${{secrets.USERNAME}}/epowe-web/build"
