name: React deploy # Workflow 이름
on: # Event 감지
  push:
    branches: prod

jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2
        
      - name: Check Node v # Node v 확인
        run: node -v
        
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
        
      - name: Create .env file
        run: echo "${{secrets.ENV_PROD}}" > .env

      - name: Install Dependencies # 의존 파일 설치
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Build # React Build
        run: npm run build
        env:
          CI: false

      - name: Delete Previous Build Folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /home/${{secrets.USERNAME}}/epowe-web/build
            ls -al

      - name: Deploy build outputs
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: ${{ secrets.PORT }}
          source: "build/*"
          strip_components: 1
          target: "/home/${{secrets.USERNAME}}/epowe-web/build"
